on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQ_RANDOM_PASSWORD: no
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: liquidaciones
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Creacion de Save-state
        run: echo "{name}={value}" >> $GITHUB_STATE

      - name: Creacion de Set-output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Configuracion de Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven

      - name: Configuración de conexión a la base de datos
        run: |
          echo "spring.datasource.url=jdbc:mysql://localhost:3306/liquidaciones" >> application.properties
          echo "spring.datasource.username=root" >> application.properties
          echo "spring.datasource.password=root" >> application.properties

      - name: Construyendo y testeando con mavaven
        run: mvn clean install
